[gearman]
    servers                    = "gearman0.coverage.net:4730,gearman1.coverage.net:4730"

[logging]
    enabled                    = true
    [logging.trace]
        file                   = ""
        stdout                 = false
        stderr                 = true
        color                  = true
    [logging.debug]
        file                   = "/tmp/coverage/debug.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.info]
        file                   = "/tmp/coverage/info.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.warn]
        file                   = "/tmp/coverage/warn.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.error]
        file                   = "/tmp/coverage/error.log"
        stdout                 = true
        stderr                 = false
        color                  = true

# [reporting]
#     enabled                    = true
#     memory                     = true
#     numgc                      = true
#     goroutines                 = true
#     timing                     = true

[Article]
    enabled                    = true

[Feed]
    enabled                    = true

[Manager]
    enabled                    = true
    startup                    = true
    [Manager.article]
        tick                   = "15s"
    [Manager.feed]
        tick                   = "30s"
        downloaddelay          = "-2h0m0s"

[Publication]
    enabled                    = true

[Search]
    enabled                    = true

[Social]
    enabled                    = true

[Stats]
    enabled                    = true
    rate                       = 1
    reconnect                  = "10m"
    statsd                     = "statsd.coverage.net:8125"

[StorageReader]
    enabled                    = true
    mongodb                    = "mongos0.coverage.net:27018,mongos1.coverage.net:27018,mongos2.coverage.net:27018"
    prefix                     = "Gear_"

[StorageWriter]
    enabled                    = true
    mongodb                    = "mongos0.coverage.net:27018,mongos1.coverage.net:27018,mongos2.coverage.net:27018"
    prefix                     = "Gear_"

[WebAPI]
    enabled                    = true
    httplisten                 = ":8080"

# Notes for setting up new storage units with different prefixes:
# prefix = "Prefix_From_Config_";
# sh.enableSharding(prefix + "Articles");
# sh.shardCollection(prefix + "Articles.Articles", { _id: 1 });
# sh.enableSharding(prefix + "Feeds");
# sh.shardCollection(prefix + "Feeds.Feeds", { _id: 1 });
# sh.shardCollection(prefix + "Feeds.FeedQ", { queue: 1 });
# sh.enableSharding(prefix + "Keywords");
# sh.shardCollection(prefix + "Keywords.Keywords", { _id: 1 });
# sh.enableSharding(prefix + "Publications");
# sh.shardCollection(prefix + "Publications.Publications", { _id: 1 });
# sh.enableSharding(prefix + "Search");
# sh.shardCollection(prefix + "Search.Search", { _id: 1 });
# sh.enableSharding(prefix + "SearchResults");
# sh.shardCollection(prefix + "SearchResults.SearchResults", { _id: 1 });
# sh.enableSharding(prefix + "URLs");
# sh.shardCollection(prefix + "URLs.URLs", { _id: 1 });

# Import all pubs:
# jq -c .[] <pubs.json | gearman -n -f Publication.Add
