[disgo]
    broadcast                  = "192.168.20.17:10000"
    listen                     = "0.0.0.0:10000"
    [disgo.etcd]
        servers                = "192.168.20.17:4001,192.168.20.18:4001,192.168.20.19:4001"

[logging]
    enabled                    = true
    [logging.trace]
        file                   = ""
        stdout                 = false
        stderr                 = true
        color                  = true
    [logging.debug]
        file                   = "/tmp/coverage/debug.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.info]
        file                   = "/tmp/coverage/info.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.warn]
        file                   = "/tmp/coverage/warn.log"
        stdout                 = true
        stderr                 = false
        color                  = true
    [logging.error]
        file                   = "/tmp/coverage/error.log"
        stdout                 = true
        stderr                 = false
        color                  = true

[Article]
    enabled                    = true

[Feed]
    enabled                    = true

[Manager]
    enabled                    = true
    startup                    = true
    [Manager.article]
        tick                   = "15s"
    [Manager.feed]
        tick                   = "30s"
        downloaddelay          = "-2h0m0s"

[Publication]
    enabled                    = true

[Search]
    enabled                    = true

[Social]
    enabled                    = true

[Stats]
    enabled                    = true
    rate                       = 1
    reconnect                  = "10m"
    statsd                     = "statsd.coverage.net:8125"

[StorageReader]
    enabled                    = true
    mongodb                    = "mongos0.coverage.net:27018,mongos1.coverage.net:27018,mongos2.coverage.net:27018"
    prefix                     = "Gear_"

[StorageWriter]
    enabled                    = true
    mongodb                    = "mongos0.coverage.net:27018,mongos1.coverage.net:27018,mongos2.coverage.net:27018"
    prefix                     = "Gear_"

[WebAPI]
    enabled                    = true
    httplisten                 = ":8080"
